name: Node.js CI with API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install API dependencies
      working-directory: ./API # Set the working directory to the API folder
      run: npm ci # Install dependencies for the API
    - name: Build API
      working-directory: ./API # Set the working directory to the API folder
      run: npm run build --if-present # Build the API if there's a build script
    - name: Test API
      working-directory: ./API # Set the working directory to the API folder
      run: npm test # Run tests for the API
